FROM ubuntu:24.04
MAINTAINER bhaas@broadinstitute.org
LABEL fork.maintainer="Jason Stajich <jasonstajich.phd@gmail.com>" \
      fork.repo="https://github.com/hyphaltip/trinityrnaseq" \
      fork.description="Unofficial fork with experimental Rust optimizations; file fork-specific issues here, not upstream"

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get -qq update && apt-get -qq -y install \
    automake \
    build-essential \
    bzip2 \
    cmake \
    curl \
    default-jre \
    fort77 \
    ftp \
    g++ \
    gcc \
    gfortran \
    git \
    libblas-dev \
    libbz2-dev \
    libcairo2-dev \
    libcurl4-openssl-dev \
    libdb-dev \
    libghc-zlib-dev \
    libjpeg-dev \
    liblzma-dev \
    libncurses-dev \
    libncurses5-dev \
    libpcre3-dev \
    libpng-dev \
    libreadline-dev \
    libssl-dev \
    libtbb-dev \
    libx11-dev \
    libxml2-dev \
    libxt-dev \
    libzmq3-dev \
    make \
    nano \
    perl \
    pkg-config \
    python3 \
    python3-dev \
    python3-pip \
    rsync \
    texlive-latex-base \
    texlive-latex-extra \
    texlive-fonts-recommended \
    tzdata \
    unzip \
    wget \
    x11-common \
    zlib1g-dev

## Perl stuff
RUN curl -L https://cpanmin.us | perl - App::cpanminus
RUN cpanm install DB_File
RUN cpanm install URI::Escape

## set up tool config and deployment area:
ENV SRC /usr/local/src
ENV BIN /usr/local/bin

## Install Rust (needed for Trinity optimizations)
RUN curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
ENV PATH="/root/.cargo/bin:${PATH}"

#####
# Install R 4.3+
ENV R_VERSION=4.3.3

WORKDIR $SRC
RUN curl https://cran.r-project.org/src/base/R-4/R-${R_VERSION}.tar.gz -o R-${R_VERSION}.tar.gz && \
    tar xvf R-${R_VERSION}.tar.gz && \
    cd R-${R_VERSION} && \
    ./configure && make && make install && \
    cd .. && rm -rf R-${R_VERSION}

RUN R -e 'install.packages("BiocManager", repos="http://cran.us.r-project.org")'
RUN R -e 'BiocManager::install("tidyverse")'
RUN R -e 'BiocManager::install("edgeR")'
RUN R -e 'BiocManager::install("DESeq2")'
RUN R -e 'BiocManager::install("ape")'
RUN R -e 'BiocManager::install("ctc")'
RUN R -e 'BiocManager::install("gplots")'
RUN R -e 'BiocManager::install("Biobase")'
RUN R -e 'BiocManager::install("qvalue")'
RUN R -e 'BiocManager::install("goseq")'
RUN R -e 'BiocManager::install("Glimma")'
RUN R -e 'BiocManager::install("ROTS")'
RUN R -e 'BiocManager::install("GOplot")'
RUN R -e 'BiocManager::install("argparse")'
RUN R -e 'BiocManager::install("fastcluster")'
RUN R -e 'BiocManager::install("DEXSeq")'
RUN R -e 'BiocManager::install("tximport")'
RUN R -e 'BiocManager::install("tximportData")'

ENV LD_LIBRARY_PATH=/usr/local/lib

## Python 3 stuff
RUN ln -sf /usr/bin/python3 /usr/bin/python
RUN pip3 install numpy
RUN pip3 install git+https://github.com/ewels/MultiQC.git
RUN pip3 install HTSeq

## bowtie
WORKDIR $SRC
RUN wget https://sourceforge.net/projects/bowtie-bio/files/bowtie/1.2.3/bowtie-1.2.3-linux-x86_64.zip/download -O bowtie-1.2.3-linux-x86_64.zip && \
    unzip -q bowtie-1.2.3-linux-x86_64.zip && \
    mv bowtie-1.2.3/bowtie* $BIN

## RSEM
RUN mkdir -p /usr/local/lib/site_perl
WORKDIR $SRC
RUN wget https://github.com/deweylab/RSEM/archive/v1.3.3.tar.gz && \
    tar xvf v1.3.3.tar.gz && \
    cd RSEM-1.3.3 && \
    make && \
    cp rsem-* convert-sam-for-rsem $BIN && \
    cp rsem_perl_utils.pm /usr/local/lib/site_perl/ && \
    cd ../ && rm -r RSEM-1.3.3

## Kallisto
WORKDIR $SRC
RUN wget https://github.com/pachterlab/kallisto/releases/download/v0.48.0/kallisto_linux-v0.48.0.tar.gz && \
    tar xvf kallisto_linux-v0.48.0.tar.gz && \
    mv kallisto/kallisto $BIN

## FASTQC
ENV FASTQC_VERSION 0.12.1
WORKDIR $SRC
RUN wget https://www.bioinformatics.babraham.ac.uk/projects/fastqc/fastqc_v${FASTQC_VERSION}.zip && \
    unzip -q fastqc_v${FASTQC_VERSION}.zip && \
    chmod 755 /usr/local/src/FastQC/fastqc && \
    ln -s /usr/local/src/FastQC/fastqc $BIN/.

# blast
WORKDIR $SRC
ENV BLASTPLUS_VERSION 2.14.1
RUN wget ftp://ftp.ncbi.nlm.nih.gov/blast/executables/blast+/${BLASTPLUS_VERSION}/ncbi-blast-${BLASTPLUS_VERSION}+-x64-linux.tar.gz && \
    tar xvf ncbi-blast-${BLASTPLUS_VERSION}+-x64-linux.tar.gz && \
    cp ncbi-blast-${BLASTPLUS_VERSION}+/bin/* $BIN && \
    rm -r ncbi-blast-${BLASTPLUS_VERSION}+

## Bowtie2
WORKDIR $SRC
ENV BOWTIE2_VERSION 2.5.3
RUN wget https://sourceforge.net/projects/bowtie-bio/files/bowtie2/${BOWTIE2_VERSION}/bowtie2-${BOWTIE2_VERSION}-linux-x86_64.zip/download -O bowtie2-${BOWTIE2_VERSION}-linux-x86_64.zip && \
    unzip -q bowtie2-${BOWTIE2_VERSION}-linux-x86_64.zip && \
    mv bowtie2-${BOWTIE2_VERSION}-linux-x86_64/bowtie2* $BIN && \
    rm -r bowtie2-${BOWTIE2_VERSION}-linux-x86_64

## Samtools
ENV SAMTOOLS_VERSION 1.19
RUN wget https://github.com/samtools/samtools/releases/download/${SAMTOOLS_VERSION}/samtools-${SAMTOOLS_VERSION}.tar.bz2 && \
    tar xvf samtools-${SAMTOOLS_VERSION}.tar.bz2 && \
    cd samtools-${SAMTOOLS_VERSION} && \
    ./configure && make && make install && \
    cd .. && rm -r samtools-${SAMTOOLS_VERSION}

## Jellyfish
ENV JELLYFISH_VERSION 2.3.0
RUN wget https://github.com/gmarcais/Jellyfish/releases/download/v${JELLYFISH_VERSION}/jellyfish-${JELLYFISH_VERSION}.tar.gz && \
    tar xvf jellyfish-${JELLYFISH_VERSION}.tar.gz && \
    cd jellyfish-${JELLYFISH_VERSION}/ && \
    ./configure && make && make install && \
    cd .. && rm -r jellyfish-${JELLYFISH_VERSION}

## FeatureCounts
ENV SUBREAD_VERSION 2.0.6
RUN wget https://sourceforge.net/projects/subread/files/subread-${SUBREAD_VERSION}/subread-${SUBREAD_VERSION}-Linux-x86_64.tar.gz/download -O subread-${SUBREAD_VERSION}-Linux-x86_64.tar.gz && \
    tar xvf subread-${SUBREAD_VERSION}-Linux-x86_64.tar.gz && \
    cp -r subread-${SUBREAD_VERSION}-Linux-x86_64/bin/* $BIN/ && \
    rm -r subread-${SUBREAD_VERSION}-Linux-x86_64

## Hisat2
WORKDIR $SRC
RUN wget https://cloud.biohpc.swmed.edu/index.php/s/oTtGWbWjaxsQ2Ho/download -O hisat2-2.2.1-Linux_x86_64.zip && \
    unzip -q hisat2-2.2.1-Linux_x86_64.zip && \
    cp hisat2-2.2.1/hisat2* $BIN/ && \
    rm -r hisat2-2.2.1

## GMAP/GSNAP
ENV GSNAP_VER 2024-05-02
WORKDIR $SRC
RUN GMAP_URL="http://research-pub.gene.com/gmap/src/gmap-gsnap-$GSNAP_VER.tar.gz" && \
    wget $GMAP_URL && \
    tar xvf gmap-gsnap-$GSNAP_VER.tar.gz && \
    cd gmap-$GSNAP_VER && ./configure --prefix=`pwd` && make && make install && \
    cp bin/* $BIN/ && \
    cd .. && rm -r gmap-$GSNAP_VER

# blat
RUN wget http://hgdownload.cse.ucsc.edu/admin/exe/linux.x86_64/blat/blat -P $BIN && \
    chmod a+x $BIN/blat

## Picard tools
WORKDIR $SRC
RUN wget https://github.com/broadinstitute/picard/releases/download/3.1.1/picard.jar

## GATK4 installation
WORKDIR $SRC
ENV GATK_VERSION=4.5.0.0
RUN wget https://github.com/broadinstitute/gatk/releases/download/${GATK_VERSION}/gatk-${GATK_VERSION}.zip && \
    unzip -q gatk-${GATK_VERSION}.zip

ENV GATK_HOME $SRC/gatk-${GATK_VERSION}

## STAR
ENV STAR_VERSION=2.7.11b
RUN STAR_URL="https://github.com/alexdobin/STAR/archive/${STAR_VERSION}.tar.gz" &&\
    wget -P $SRC $STAR_URL &&\
    tar -xvf $SRC/${STAR_VERSION}.tar.gz -C $SRC && \
    mv $SRC/STAR-${STAR_VERSION}/bin/Linux_x86_64_static/STAR /usr/local/bin && \
    rm -r $SRC/STAR-${STAR_VERSION}

## Salmon
WORKDIR $SRC
ENV SALMON_VERSION=1.10.3
RUN wget https://github.com/COMBINE-lab/salmon/releases/download/v${SALMON_VERSION}/salmon-${SALMON_VERSION}_linux_x86_64.tar.gz -O salmon-${SALMON_VERSION}_linux_x86_64.tar.gz && \
    tar xvf salmon-${SALMON_VERSION}_linux_x86_64.tar.gz && \
    ln -s $SRC/salmon-${SALMON_VERSION}_linux_x86_64/bin/salmon $BIN/. && \
    rm -r salmon-${SALMON_VERSION}_linux_x86_64

## Trinity (with Rust optimizations branch)
WORKDIR $SRC
ENV TRINITY_VERSION="2.16.1_rust"
ENV TRINITY_BRANCH="rust_optimize"

RUN git clone --recursive https://github.com/hyphaltip/trinityrnaseq.git && \
    cd trinityrnaseq && \
    git checkout ${TRINITY_BRANCH} && \
    git submodule init && git submodule update && \
    git submodule foreach --recursive git submodule init && \
    git submodule foreach --recursive git submodule update && \
    rm -rf ./trinity_ext_sample_data && \
    make all && make plugins && \
    make install && \
    # Verify Rust binaries were built
    ls -lh rust_bio_utils/target/release/ | head -10 && \
    cd ../ && rm -r trinityrnaseq

ENV TRINITY_HOME /usr/local/bin
ENV PATH=${TRINITY_HOME}:${PATH}

# Cleanup
WORKDIR $SRC
RUN rm -rf *.tar.gz *.tar.bz2 *.zip && \
    apt-get -qq -y autoremove && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/* /var/log/dpkg.log

################################################
## Be sure this is last!
WORKDIR /
RUN echo "Trinity with Rust optimizations (${TRINITY_BRANCH}) built on $(date)" > /TRINITY_BUILD_INFO.txt
COPY Dockerfile.ubuntu24 $SRC/Dockerfile.${TRINITY_VERSION}
